"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { programOfferings, sessions } from "../lib/camp-catalog";

type Interest = { count: number; priority: string; note: string };
type FormState = {
  unitType: string; unitNumber: string; council: string; city: string; state: string; sessionId: string;
  youthMale: number; youthFemale: number; youthOther: number; adultMale: number; adultFemale: number; adultOther: number;
  contactName: string; contactEmail: string; contactPhone: string; alternateName: string; alternateEmail: string;
  scouts: string[]; interests: Record<string, Interest>; accommodationFollowUp: boolean;
};

const empty: FormState = { unitType: "Troop", unitNumber: "", council: "Catalina Council", city: "", state: "AZ", sessionId: "bsa-week-2", youthMale: 0, youthFemale: 0, youthOther: 0, adultMale: 0, adultFemale: 0, adultOther: 0, contactName: "", contactEmail: "", contactPhone: "", alternateName: "", alternateEmail: "", scouts: [], interests: {}, accommodationFollowUp: false };
const steps = ["Unit", "Contacts", "Scout names", "Badge interest", "Review"];

export default function PreRegisterClient() {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>(empty);
  const [scoutName, setScoutName] = useState("");
  const [status, setStatus] = useState("");
  const [reference, setReference] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { const saved = localStorage.getItem("camp-lawton-preregistration"); if (saved) try { setForm(JSON.parse(saved)); } catch {} }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { localStorage.setItem("camp-lawton-preregistration", JSON.stringify(form)); }, [form]);
  const youthTotal = form.youthMale + form.youthFemale + form.youthOther;
  const adultTotal = form.adultMale + form.adultFemale + form.adultOther;
  const selectedSession = sessions.find((session) => session.id === form.sessionId);
  const interestRows = useMemo(() => programOfferings.filter((offering) => (form.interests[offering.id]?.count ?? 0) > 0), [form.interests]);
  const update = (name: keyof FormState, value: FormState[keyof FormState]) => setForm((current) => ({ ...current, [name]: value }));
  const updateCount = (name: keyof FormState, value: string) => update(name, Math.max(0, Math.min(250, Number(value) || 0)) as never);
  const validStep = step === 0 ? Boolean(form.unitNumber && form.sessionId && youthTotal > 0 && adultTotal > 0) : step === 1 ? Boolean(form.contactName && /\S+@\S+\.\S+/.test(form.contactEmail)) : true;
  const addScout = () => { const name = scoutName.trim(); if (!name || form.scouts.length >= youthTotal) return; update("scouts", [...form.scouts, name]); setScoutName(""); };
  const setInterest = (id: string, patch: Partial<Interest>) => setForm((current) => {
    const previous = current.interests[id] ?? { count: 0, priority: "nice-to-have", note: "" };
    return { ...current, interests: { ...current.interests, [id]: { ...previous, ...patch } } };
  });

  async function submit() {
    setStatus("Submitting...");
    const response = await fetch("/api/pre-register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, consent: true, website: "" }) });
    const result = await response.json() as { reference?: string; error?: string };
    if (!response.ok || !result.reference) { setStatus(result.error ?? "Submission could not be completed."); return; }
    setReference(result.reference); setStatus(""); localStorage.removeItem("camp-lawton-preregistration");
  }

  if (reference) return <div className="submission-confirmation" role="status"><span>Planning submission received</span><h2>{reference}</h2><p>Keep this reference with your unit records. This submission does not register participants, reserve a campsite, guarantee badge seats, or replace Black Pug registration.</p><Link className="button" href="/">Return home</Link></div>;

  return <div className="prereg-app"><ol className="stepper">{steps.map((label, index) => <li key={label} className={index === step ? "active" : index < step ? "complete" : ""}><span>{index + 1}</span><strong>{label}</strong></li>)}</ol><div className="prereg-disclaimer"><strong>Planning only</strong><p>This non-binding survey does not reserve a campsite, register participants, guarantee merit badge seats, or collect payment. Official registration will be available separately through Black Pug.</p></div>
    {step === 0 && <section className="form-step"><header><span>Step 1</span><h2>Unit and attendance</h2><p>Use aggregate counts. Do not enter birth dates, health details, or other sensitive youth information.</p></header><div className="form-grid"><label><span>Unit type</span><select value={form.unitType} onChange={(event) => update("unitType", event.target.value)}><option>Troop</option><option>Pack</option><option>Crew</option></select></label><label><span>Unit number</span><input value={form.unitNumber} onChange={(event) => update("unitNumber", event.target.value)} required /></label><label><span>Council</span><input value={form.council} onChange={(event) => update("council", event.target.value)} /></label><label><span>City</span><input value={form.city} onChange={(event) => update("city", event.target.value)} /></label><label><span>State</span><input value={form.state} maxLength={2} onChange={(event) => update("state", event.target.value.toUpperCase())} /></label><label><span>Preferred session</span><select value={form.sessionId} onChange={(event) => update("sessionId", event.target.value)}>{sessions.map((session) => <option value={session.id} key={session.id}>{session.name} · {session.dates}</option>)}</select></label></div><h3>Estimated participants</h3><div className="count-grid">{[["youthMale", "Youth · male"], ["youthFemale", "Youth · female"], ["youthOther", "Youth · another / not listed"], ["adultMale", "Adults · male"], ["adultFemale", "Adults · female"], ["adultOther", "Adults · another / not listed"]].map(([name, label]) => <label key={name}><span>{label}</span><input type="number" min="0" max="250" value={form[name as keyof FormState] as number} onChange={(event) => updateCount(name as keyof FormState, event.target.value)} /></label>)}</div><label className="form-check"><input type="checkbox" checked={form.accommodationFollowUp} onChange={(event) => update("accommodationFollowUp", event.target.checked)} /><span>Ask camp staff to follow up about accessibility, dietary, or accommodation planning. Do not enter health details here.</span></label></section>}
    {step === 1 && <section className="form-step"><header><span>Step 2</span><h2>Adult contacts</h2><p>Camp staff use these contacts only for this planning submission and official-registration follow-up.</p></header><div className="form-grid"><label><span>Primary adult name</span><input value={form.contactName} onChange={(event) => update("contactName", event.target.value)} /></label><label><span>Email</span><input type="email" value={form.contactEmail} onChange={(event) => update("contactEmail", event.target.value)} /></label><label><span>Phone</span><input type="tel" value={form.contactPhone} onChange={(event) => update("contactPhone", event.target.value)} /></label><label><span>Alternate adult name</span><input value={form.alternateName} onChange={(event) => update("alternateName", event.target.value)} /></label><label><span>Alternate email</span><input type="email" value={form.alternateEmail} onChange={(event) => update("alternateEmail", event.target.value)} /></label></div></section>}
    {step === 2 && <section className="form-step"><header><span>Step 3</span><h2>Optional Scout display names</h2><p>Names help connect planning demand to individual schedules. Enter a first name and last initial when practical. This form never asks for birth dates or medical information.</p></header><div className="roster-entry"><input value={scoutName} onChange={(event) => setScoutName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); addScout(); } }} placeholder="First name and last initial" maxLength={80} /><button type="button" onClick={addScout} disabled={!scoutName.trim() || form.scouts.length >= youthTotal}>Add Scout</button></div><div className="roster-list">{form.scouts.map((name, index) => <div key={`${name}-${index}`}><span>{index + 1}</span><strong>{name}</strong><button aria-label={`Remove ${name}`} onClick={() => update("scouts", form.scouts.filter((_, position) => position !== index))}>×</button></div>)}{form.scouts.length === 0 && <p>No names added. You can continue with aggregate counts only.</p>}</div><small>{form.scouts.length} of {youthTotal} estimated youth named</small></section>}
    {step === 3 && <section className="form-step interest-step"><header><span>Step 4</span><h2>Merit badge demand</h2><p>Enter estimated interest and priority. This data informs which classes camp should offer; it is not enrollment.</p></header><div className="interest-table"><div className="interest-head"><span>Badge</span><span>Interested</span><span>Priority</span></div>{programOfferings.map((offering) => { const interest = form.interests[offering.id] ?? { count: 0, priority: "nice-to-have", note: "" }; return <div key={offering.id} className={interest.count > 0 ? "selected" : ""}><div><span>{offering.area}</span><strong>{offering.title}</strong><small>{offering.viability}</small></div><input aria-label={`${offering.title} interested Scouts`} type="number" min="0" max={youthTotal || 250} value={interest.count} onChange={(event) => setInterest(offering.id, { count: Math.max(0, Number(event.target.value) || 0) })} /><select aria-label={`${offering.title} priority`} value={interest.priority} onChange={(event) => setInterest(offering.id, { priority: event.target.value })}><option value="must-have">Must-have</option><option value="strong">Strong interest</option><option value="nice-to-have">Nice-to-have</option></select></div>})}</div></section>}
    {step === 4 && <section className="form-step review-step"><header><span>Step 5</span><h2>Review and consent</h2><p>Confirm the planning snapshot before submitting.</p></header><dl><div><dt>Unit</dt><dd>{form.unitType} {form.unitNumber} · {form.city}{form.city && form.state ? ", " : ""}{form.state}</dd></div><div><dt>Session</dt><dd>{selectedSession?.name} · {selectedSession?.dates}</dd></div><div><dt>Attendance</dt><dd>{youthTotal} youth · {adultTotal} adults</dd></div><div><dt>Contact</dt><dd>{form.contactName} · {form.contactEmail}</dd></div><div><dt>Scout names</dt><dd>{form.scouts.length ? form.scouts.join(", ") : "Aggregate counts only"}</dd></div><div><dt>Badge demand</dt><dd>{interestRows.length ? interestRows.map((item) => `${item.title}: ${form.interests[item.id].count}`).join(" · ") : "No badge interests entered"}</dd></div></dl><div className="consent-copy"><strong>By submitting, you confirm:</strong><p>You are authorized to share this unit planning information; the counts are estimates; this is not official registration; badge seats are not guaranteed; and camp staff may contact the listed adults about 2027 planning. Records are scheduled for deletion after the season closeout period.</p></div>{status && <p className="submission-error" role="status">{status}</p>}</section>}
    <div className="form-navigation"><button type="button" className="button button-secondary" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>Back</button>{step < 4 ? <button type="button" className="button" onClick={() => setStep(step + 1)} disabled={!validStep}>Continue</button> : <button type="button" className="button" onClick={submit} disabled={status === "Submitting..."}>Submit planning survey</button>}</div>
  </div>;
}
