export type MapCategory = "campsite" | "program" | "amenity";

export type MapPoint = {
  x: number;
  y: number;
  label?: string;
};

export type CampMapLocation = {
  id: string;
  title: string;
  category: MapCategory;
  x: number;
  y: number;
  description: string;
  nearby: string;
  practical?: string;
  image?: string;
  imageAlt?: string;
  gallery?: { src: string; alt: string }[];
  points?: MapPoint[];
};

export const mapCategoryLabels: Record<MapCategory, string> = {
  campsite: "Campsites",
  program: "Program areas",
  amenity: "Camp facilities",
};

export const campMapLocations: CampMapLocation[] = [
  {
    id: "staff-hill",
    title: "Staff Hill",
    category: "amenity",
    x: 41.4,
    y: 18.2,
    description: "The staff building cluster at the north end of camp, just inside the Organization Ridge Road approach.",
    nearby: "North of Oglala campsite and west of Navajo campsite.",
    practical: "This is a staff area. Check with the Camp Office before heading up the hill.",
  },
  {
    id: "navajo",
    title: "Navajo campsite",
    category: "campsite",
    x: 66.3,
    y: 25.7,
    image: "/map/locations/campsite-navajo.webp",
    imageAlt: "Illustrated Navajo campsite badge",
    description: "The northernmost campsite, set close to the Organization Ridge Road side of the property.",
    nearby: "Above STEM and northeast of Al’s Well.",
    practical: "Navajo has direct vehicle access and is usually held for units that need that accommodation. Confirm every vehicle movement with camp staff.",
  },
  {
    id: "santa-cruz",
    title: "Santa Cruz campsite",
    category: "campsite",
    x: 22.3,
    y: 28.4,
    image: "/map/locations/campsite-santa-cruz.webp",
    imageAlt: "Illustrated Santa Cruz campsite badge",
    description: "A northwestern campsite on the trail descending from Staff Hill.",
    nearby: "North of Pima campsite and across camp from Navajo.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "smellables-shed",
    title: "Smellables Shed",
    category: "amenity",
    x: 50.8,
    y: 31.2,
    description: "The small storage point shown between Staff Hill, Oglala campsite, and Al’s Well.",
    nearby: "On the upper central trail network, west of Al’s Well.",
    practical: "Follow staff directions for food and scented-item storage. Wildlife-safe storage rules apply throughout camp.",
  },
  {
    id: "north-latrines",
    title: "Latrines",
    category: "amenity",
    x: 28,
    y: 37,
    image: "/map/locations/latrines.webp",
    imageAlt: "Black line illustration of a camp latrine",
    description: "Latrine symbols appear in several campsite and program loops. Select any marker to open this shared guide.",
    nearby: "Distributed across the west, north, central, and eastern sides of camp.",
    practical: "Use the facility assigned or identified during orientation and report service concerns to staff.",
    points: [
      { x: 28, y: 37, label: "Northwest latrine" },
      { x: 54.2, y: 31.1, label: "North-central latrine" },
      { x: 69.5, y: 33, label: "Northeast latrine" },
      { x: 20.6, y: 49, label: "West latrine" },
      { x: 26.6, y: 55.2, label: "Central-west latrine" },
      { x: 68.8, y: 69.6, label: "Southeast latrine" },
      { x: 29.4, y: 72.7, label: "Southwest latrine" },
    ],
  },
  {
    id: "als-well",
    title: "Al’s Well",
    category: "amenity",
    x: 58.1,
    y: 35.5,
    description: "A historic camp landmark tied to the spring system that helped shape Camp Lawton’s permanent home.",
    nearby: "Between Oglala campsite, STEM, and the Dining Hall approach.",
    practical: "Treat the well as a landmark; use only staff-designated sources for drinking water.",
  },
  {
    id: "oglala",
    title: "Oglala campsite",
    category: "campsite",
    x: 38.4,
    y: 35.6,
    image: "/map/locations/campsite-oglala.webp",
    imageAlt: "Illustrated Oglala campsite badge",
    description: "An upper central-west campsite connected to both Staff Hill and the main camp trail network.",
    nearby: "East of Pima, north of Zuni, and west of Al’s Well.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "stem",
    title: "STEM",
    category: "program",
    x: 71.8,
    y: 37,
    image: "/map/locations/stem.webp",
    imageAlt: "Illustrated STEM program emblem with science and technology symbols",
    description: "The science and technology program area on the upper east side of the central camp loop.",
    nearby: "Below Navajo campsite and just north of the Camp Office.",
    practical: "Use this map for orientation; activities and meeting times will appear only in final authorized program information.",
  },
  {
    id: "pima",
    title: "Pima campsite",
    category: "campsite",
    x: 20.8,
    y: 38.3,
    image: "/map/locations/campsite-pima.webp",
    imageAlt: "Illustrated Pima campsite badge",
    description: "A western campsite midway down the upper campsite trail.",
    nearby: "South of Santa Cruz, west of Oglala, and north of Gila.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "camp-office",
    title: "Camp Office",
    category: "amenity",
    x: 71.2,
    y: 43.1,
    description: "The central check-in and staff contact point shown beside the main camp road.",
    nearby: "South of STEM, west of Eagle Quest, and northeast of the Parade Grounds.",
    practical: "Start here when you need camp staff direction, have a site question, or need to report a non-emergency concern.",
  },
  {
    id: "eagle-quest",
    title: "Eagle Quest",
    category: "program",
    x: 79.9,
    y: 46.6,
    image: "/map/locations/eagle-quest.webp",
    imageAlt: "Illustrated Eagle Quest program emblem",
    description: "A program area on the eastern edge of the central camp activity loop.",
    nearby: "East of the Camp Office and above First Aid.",
    practical: "Activities and age guidance remain in development; check the authorized program information when it is published.",
  },
  {
    id: "dining-hall",
    title: "Dining Hall",
    category: "amenity",
    x: 57.4,
    y: 48.3,
    image: "/images/history/dining-hall-aerial.jpg",
    imageAlt: "Aerial view of Camp Lawton’s connected dining hall buildings and stone chimney",
    description: "Camp’s central meal and gathering building, positioned on the main north–south road.",
    nearby: "Beside the Parade Grounds and north of Nature.",
    practical: "The Dining Hall is the primary storm shelter unless staff directs otherwise. Continuous ringing of its large bell is the campwide emergency alarm.",
  },
  {
    id: "campfire",
    title: "Campfire areas",
    category: "program",
    x: 28.5,
    y: 47.4,
    image: "/map/locations/campfire.webp",
    imageAlt: "Black line illustration of a campfire",
    description: "The map marks a smaller western fire ring and the main lower-camp gathering fire area.",
    nearby: "One is west of Oglala; the larger gathering area is between Chapel and the ranges.",
    practical: "Fire restrictions can change without warning. Use a fire only when current conditions and camp staff explicitly allow it.",
    points: [
      { x: 28.5, y: 47.4, label: "West campfire area" },
      { x: 49.7, y: 82.9, label: "Lower campfire area" },
    ],
  },
  {
    id: "parade-grounds",
    title: "Parade Grounds",
    category: "amenity",
    x: 66.2,
    y: 49.8,
    description: "The open assembly area beside the Dining Hall, marked by the flagpoles on the printed map.",
    nearby: "South of the Camp Office and east of the Dining Hall.",
    practical: "This is the primary campwide emergency assembly point. During an alarm, follow staff direction and report here for accountability.",
  },
  {
    id: "gila",
    title: "Gila campsite",
    category: "campsite",
    x: 15.8,
    y: 52.9,
    image: "/map/locations/campsite-gila.webp",
    imageAlt: "Illustrated Gila campsite badge",
    description: "A western campsite on the long loop below Pima.",
    nearby: "West of Zuni and north of Yuma.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "zuni",
    title: "Zuni campsite",
    category: "campsite",
    x: 34.2,
    y: 55,
    image: "/map/locations/campsite-zuni.webp",
    imageAlt: "Illustrated Zuni campsite badge",
    description: "A central-west campsite where the western loops meet the program-area trails.",
    nearby: "Below Oglala and near Adult Showers and Nature.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "nature",
    title: "Nature",
    category: "program",
    x: 50.7,
    y: 55.6,
    image: "/map/locations/nature.webp",
    imageAlt: "Illustrated Nature program emblem with trees, mountains, a bird, and a stream",
    description: "The centrally placed nature program area, where campsite paths meet the main road.",
    nearby: "East of Zuni, south of the Dining Hall, and west of Handicraft.",
    practical: "Use established trails between activities and allow enough transition time from the outer campsites.",
  },
  {
    id: "adult-showers",
    title: "Adult Showers",
    category: "amenity",
    x: 44.1,
    y: 57.2,
    description: "The adult shower facility shown on the central trail between Zuni and Nature.",
    nearby: "Just west of Nature and north of Scoutcraft.",
    practical: "Follow posted access and privacy rules, and use only the facilities designated for your group.",
  },
  {
    id: "first-aid",
    title: "First Aid",
    category: "amenity",
    x: 78.4,
    y: 59.2,
    description: "The first-aid point marked by the red medical symbol on the east side of camp.",
    nearby: "East of Handicraft and south of Eagle Quest.",
    practical: "For urgent or serious concerns, notify camp staff immediately and follow the camp emergency plan.",
  },
  {
    id: "handicraft",
    title: "Handicraft",
    category: "program",
    x: 64.8,
    y: 59.2,
    image: "/map/locations/handicraft.webp",
    imageAlt: "Illustrated Handicraft program emblem with scissors, paintbrushes, yarn, and thread",
    description: "The craft program area on the east side of the central activity loop.",
    nearby: "East of Nature, west of First Aid, and north of Apache campsite.",
    practical: "Potential activities are still under review. Wait for the authorized program listing before making individual plans.",
  },
  {
    id: "scoutcraft",
    title: "Scoutcraft",
    category: "program",
    x: 51.1,
    y: 64.2,
    image: "/map/locations/scoutcraft.webp",
    imageAlt: "Black line illustration of a pioneering tower for Scoutcraft",
    description: "The outdoor-skills program area in lower central camp.",
    nearby: "Below Nature, west of Handicraft, and north of Model Camp.",
    practical: "Final skill instruction, project periods, and equipment guidance will be published after program approval.",
  },
  {
    id: "apache",
    title: "Apache campsite",
    category: "campsite",
    x: 73,
    y: 65.2,
    image: "/map/locations/campsite-apache.webp",
    imageAlt: "Illustrated Apache campsite badge",
    description: "An eastern campsite tucked below Handicraft on the lower camp trail.",
    nearby: "South of First Aid and north of Cochise campsite.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "yuma",
    title: "Yuma campsite",
    category: "campsite",
    x: 19,
    y: 69,
    image: "/map/locations/campsite-yuma.webp",
    imageAlt: "Illustrated Yuma campsite badge",
    description: "A southwestern campsite on the outer west trail.",
    nearby: "South of Gila and northwest of Hopi and Hohokam.",
    practical: "This is one of the farther sites from the central program areas, so include walking time in the day plan.",
  },
  {
    id: "model-camp",
    title: "Model Camp",
    category: "program",
    x: 42.5,
    y: 69.8,
    image: "/map/locations/model-camp.webp",
    imageAlt: "Illustrated Model Camp emblem with a tent and pine trees",
    description: "A lower-camp outdoor skills area shown between Scoutcraft and the range trail.",
    nearby: "Southeast of Hohokam and southwest of Apache campsite.",
    practical: "This area may support first-year or rank skills; the final 2027 format has not been approved.",
  },
  {
    id: "cochise",
    title: "Cochise campsite",
    category: "campsite",
    x: 76.3,
    y: 73.7,
    image: "/map/locations/campsite-cochise.webp",
    imageAlt: "Illustrated Cochise campsite badge",
    description: "The southeastern campsite at the end of the lower eastern trail.",
    nearby: "Below Apache and east of Chapel.",
    practical: "This is one of the farther sites from the Dining Hall and upper program areas, so plan transition time.",
  },
  {
    id: "hopi",
    title: "Hopi campsite",
    category: "campsite",
    x: 11.8,
    y: 76.7,
    image: "/map/locations/campsite-hopi.webp",
    imageAlt: "Illustrated Hopi campsite badge",
    description: "The far southwestern campsite, set below Yuma on the outer loop.",
    nearby: "West of Hohokam and well southwest of Model Camp.",
    practical: "This is one of the farther sites from the central program areas, so include walking time in the day plan.",
  },
  {
    id: "hohokam",
    title: "Hohokam campsite",
    category: "campsite",
    x: 24,
    y: 79.7,
    image: "/map/locations/campsite-hohokam.webp",
    imageAlt: "Illustrated Hohokam campsite badge",
    description: "A lower southwestern campsite on the trail leading toward Model Camp.",
    nearby: "East of Hopi, south of Yuma, and west of Model Camp.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "chapel",
    title: "Chapel",
    category: "program",
    x: 63.9,
    y: 81.3,
    image: "/images/history/clayton-herbert-chapel.jpeg",
    imageAlt: "The open-air Clayton Herbert Memorial Chapel with its stone altar and log benches among the pines",
    gallery: [
      { src: "/map/locations/chapel.webp", alt: "Illustrated chapel emblem with an open book and rising sun" },
    ],
    description: "The open-air Clayton Herbert Memorial Chapel, a quiet reflection space in lower camp.",
    nearby: "Southwest of Cochise and north of the main campfire and ranges.",
    practical: "Camp staff will announce any chapel, Scouts’ Own, or unit reflection opportunities for the session.",
  },
  {
    id: "archery",
    title: "Archery Range",
    category: "program",
    x: 36.9,
    y: 88.4,
    image: "/map/locations/archery.webp",
    imageAlt: "Black line illustration of an arrow in an archery target",
    description: "The archery range at the southwest end of the lower camp activity trail.",
    nearby: "Below the main campfire area and west of the Rifle Range.",
    practical: "Range availability is not final and always depends on approval, qualified supervision, and posted procedures.",
  },
  {
    id: "rifle-range",
    title: "Rifle Range",
    category: "program",
    x: 55.4,
    y: 91.6,
    image: "/map/locations/rifle-range.webp",
    imageAlt: "Black line illustration of a rifle inside a circle",
    description: "The shooting-sports range at the southern edge of the mapped camp.",
    nearby: "Southeast of Archery and below the main campfire area.",
    practical: "Air-rifle programming runs only when approvals, equipment, range procedures, permit conditions, and qualified staff are all in place.",
  },
];
