export type HistoryCategory = "origins" | "infrastructure" | "tradition" | "resilience" | "renewal";

export type HistoryEraId = "finding" | "building" | "enduring" | "next";

export type HistoryEvent = {
  id: string;
  year: string;
  sortYear: number;
  title: string;
  summary: string;
  detail: string;
  significance: string;
  category: HistoryCategory;
  era: HistoryEraId;
  image?: {
    src: string;
    alt: string;
    caption: string;
  };
};

export const historyCategories: { id: "all" | HistoryCategory; label: string }[] = [
  { id: "all", label: "All stories" },
  { id: "origins", label: "Origins" },
  { id: "infrastructure", label: "Built by hand" },
  { id: "tradition", label: "Traditions" },
  { id: "resilience", label: "Resilience" },
  { id: "renewal", label: "Renewal" },
];

export const historyEras: {
  id: HistoryEraId;
  range: string;
  title: string;
  shortTitle: string;
  copy: string;
}[] = [
  {
    id: "finding",
    range: "1910–1933",
    title: "Finding the mountain",
    shortTitle: "Finding the mountain",
    copy: "Scouting reaches Arizona, Tucson builds a council, and a summer refuge takes root high above the desert.",
  },
  {
    id: "building",
    range: "1947–1966",
    title: "Built by many hands",
    shortTitle: "Built by many hands",
    copy: "Springs, lodges, a pool, and a chapel turn a rugged campsite into a permanent outdoor campus.",
  },
  {
    id: "enduring",
    range: "1986–2021",
    title: "Tested by the mountain",
    shortTitle: "Tested & renewed",
    copy: "Fire, snow, and changing expectations reshape the camp without erasing the traditions at its center.",
  },
  {
    id: "next",
    range: "2025–2026",
    title: "The next ascent",
    shortTitle: "The next ascent",
    copy: "A difficult financial chapter leads to local independence and a compact new model for summer camp.",
  },
];

export const historyEvents: HistoryEvent[] = [
  {
    id: "scouting-arrives",
    year: "1910",
    sortYear: 1910,
    title: "Scouting arrives in Arizona",
    summary: "The territory’s first Boy Scout troops form in Prescott and Tombstone, creating the foundation for organized Scouting across Arizona.",
    detail: "The movement reached Arizona before statehood. Troops soon followed in Phoenix, Tucson, Bisbee, and Globe, while Tucson Scouts used places such as the old Fort Lowell grounds for early outings and skills practice.",
    significance: "Camp Lawton grew from a regional movement that was already looking for permanent places where young people could learn outdoors.",
    category: "origins",
    era: "finding",
  },
  {
    id: "lawton-arrives",
    year: "1914",
    sortYear: 1914,
    title: "James M. Lawton comes to Tucson",
    summary: "The Harvard-educated accountant builds the civic and financial relationships that help professionalize local Scouting.",
    detail: "Lawton became the first president of the Tucson Council of Boy Scouts. His accounting expertise, community relationships, and commitment to youth development gave the young council the structure it needed to grow.",
    significance: "The mountain camp would later carry his name in recognition of that formative leadership.",
    category: "origins",
    era: "finding",
  },
  {
    id: "camp-founded",
    year: "1921",
    sortYear: 1921,
    title: "A camp is founded above the desert",
    summary: "The new Rotary Club of Tucson makes a Boy Scout camp its first community project, raising $400 for a site near today’s Palisades Ranger Station.",
    detail: "Sixty-eight boys attended the inaugural summer sessions. Rotary members helped keep camp within reach for families, subsidizing a fee that remained only $2 per week into the middle of the decade.",
    significance: "A civic promise became a physical place—and began a partnership of donations, materials, and volunteer labor that would last for generations.",
    category: "origins",
    era: "finding",
    image: {
      src: "/images/camp-sign.jpg",
      alt: "The wooden Camp Lawton entrance sign among ponderosa pines",
      caption: "The entrance to Camp Lawton today, more than a century after the first summer session.",
    },
  },
  {
    id: "tribe-founded",
    year: "1923",
    sortYear: 1923,
    title: "A local honor tradition begins",
    summary: "Camp Director and Scout Executive Harry Ogle establishes the Tribe of Papago to recognize camping skill, leadership, and service.",
    detail: "Ogle created a four-stage progression—Hunter, Warrior, Medicine Man, and Chief—at a time when local honor-camper societies were appearing at camps across the country. The organization became deeply woven into Camp Lawton culture.",
    significance: "Service to the camp became more than maintenance; it became a way generations learned belonging and responsibility.",
    category: "tradition",
    era: "finding",
  },
  {
    id: "relocation",
    year: "1926",
    sortYear: 1926,
    title: "Camp moves in search of water",
    summary: "The original site cannot support a growing summer population, so the camp relocates down Organization Ridge to its present footprint.",
    detail: "The new location offered two essential advantages: nearby mountain springs and access to an established telephone line for emergencies and coordination with Tucson.",
    significance: "Water—not scenery—determined the camp’s permanent home and would shape nearly every major improvement that followed.",
    category: "infrastructure",
    era: "finding",
  },
  {
    id: "control-road",
    year: "1933",
    sortYear: 1933,
    title: "The road finally reaches camp",
    summary: "A federal prison work crew uses the camp as a base while extending the rough Control Road to the property.",
    detail: "Before the extension, reaching Camp Lawton meant navigating a narrow, time-controlled dirt route from Oracle. Youth camping moved elsewhere for the 1933 season while the road connection was completed.",
    significance: "Reliable vehicle access changed what the camp could build, supply, and safely support.",
    category: "infrastructure",
    era: "finding",
  },
  {
    id: "als-well",
    year: "1947",
    sortYear: 1947,
    title: "Al’s Well secures the water supply",
    summary: "Engineer and hydrologist Al Christensen develops three mountain springs into a dependable camp water system.",
    detail: "Christensen’s volunteer engineering connected and stabilized the springs that sustained drinking, cooking, and sanitation. The primary spring and wishing well were dedicated as “Al’s Well.”",
    significance: "The water system unlocked the postwar building boom and still represents the camp’s most fundamental relationship with the mountain.",
    category: "infrastructure",
    era: "building",
  },
  {
    id: "dining-hall-roof",
    year: "1947",
    sortYear: 1947.1,
    title: "The dining hall begins to rise",
    summary: "Volunteers erect the large central roof that will become the camp’s social and logistical heart.",
    detail: "The kitchen and main hall were completed the following year, giving Camp Lawton a permanent place to feed and gather a growing summer population.",
    significance: "The dining hall translated a dependable water supply into a true shared campus.",
    category: "infrastructure",
    era: "building",
  },
  {
    id: "health-lodge",
    year: "1948",
    sortYear: 1948,
    title: "A permanent health lodge opens",
    summary: "The camp creates a dedicated medical facility and names it in memory of Eagle Scout Bobby Morrow.",
    detail: "The lodge provided a permanent place for triage, care, and isolation—an important marker of Camp Lawton’s transition from temporary summer site to a professionally supported campus.",
    significance: "Growth was paired with a more deliberate commitment to health and safety.",
    category: "infrastructure",
    era: "building",
  },
  {
    id: "camp-office",
    year: "1949",
    sortYear: 1949,
    title: "The camp office becomes the nerve center",
    summary: "A permanent administrative office is built near the entrance and dedicated to former council president Roy H. Robison.",
    detail: "From this small log building, generations of staff coordinated arrivals, communications, records, emergencies, and the thousand daily details of camp life.",
    significance: "A handmade building became the operational front door to Camp Lawton.",
    category: "infrastructure",
    era: "building",
    image: {
      src: "/images/camp-office.jpg",
      alt: "Camp Lawton’s log camp office beneath tall pine trees",
      caption: "The Roy H. Robison Camp Office remains one of the property’s defining log structures.",
    },
  },
  {
    id: "butler-nature",
    year: "1951",
    sortYear: 1951,
    title: "Camp grows room to gather and learn",
    summary: "Butler Hall expands dining capacity while the Dr. Streets Nature Lodge gives ecological education a permanent home.",
    detail: "The Nature Lodge honored University of Arizona professor R. B. Streets, who volunteered his time teaching biology and nature at camp. Together, the new buildings reflected both rapid growth and a broader educational mission.",
    significance: "Camp Lawton’s physical plant began to mirror the full range of its program—from shared meals to close observation of the Sky Island ecosystem.",
    category: "infrastructure",
    era: "building",
    image: {
      src: "/images/nature-lodge.jpg",
      alt: "The rustic Camp Lawton Nature Lodge surrounded by pine trees",
      caption: "The Nature Lodge carries forward the camp’s long connection between outdoor learning and place.",
    },
  },
  {
    id: "papago-lodge",
    year: "1953",
    sortYear: 1953,
    title: "Papago Lodge 494 is chartered",
    summary: "Camp Lawton’s honor tradition connects with the national Order of the Arrow through a new Catalina Council lodge.",
    detail: "Norman R. Horwitz led the transition and conducted the first Ordeal, inducting 84 Arrowmen. The earlier camp society continued as a service and alumni tradition rather than disappearing outright.",
    significance: "A distinctly local culture found a place within a national Scouting framework while preserving its focus on service.",
    category: "tradition",
    era: "building",
  },
  {
    id: "disneyland-story",
    year: "1956",
    sortYear: 1956,
    title: "A staff story enters camp folklore",
    summary: "Director Cliff Waetje closes an intense summer by taking his staff to the newly opened Disneyland.",
    detail: "The unusual excursion survives in the source documents as a vivid snapshot of the loyalty, improvisation, and close-knit staff culture that developed on the mountain.",
    significance: "Camp history is carried not only in buildings, but also in the stories staff tell the next staff.",
    category: "tradition",
    era: "building",
  },
  {
    id: "ranger-cabin",
    year: "1957",
    sortYear: 1957,
    title: "A year-round home for the ranger",
    summary: "Contractors, Scouts, Scouters, and volunteers work together to complete the Ranger Cabin near the front gate.",
    detail: "The cabin established a permanent caretaker presence, helping the council protect and maintain an isolated property through winter weather and the long off-season.",
    significance: "Stewardship of the camp became a year-round responsibility rather than a summer task.",
    category: "infrastructure",
    era: "building",
  },
  {
    id: "pool-opens",
    year: "1958",
    sortYear: 1958,
    title: "An alpine pool opens at 7,900 feet",
    summary: "Scouters Bryce Liming and Lyle Bull lead the ambitious effort to build a concrete swimming pool high on the mountain.",
    detail: "The pool made swimming, lifesaving, and water-rescue instruction possible at camp. It also inspired the “Llama Lunge,” a famously cold early-morning tradition for staff and campers.",
    significance: "Engineering expanded the program—and created one of Camp Lawton’s most memorable tests of nerve.",
    category: "infrastructure",
    era: "building",
  },
  {
    id: "accreditation",
    year: "1962",
    sortYear: 1962,
    title: "National standards recognize the camp",
    summary: "Camp Lawton earns its first National Camping School accreditation.",
    detail: "The certification validated decades of work on facilities, training, safety, and program quality, placing the camp within a consistent national framework for resident camping.",
    significance: "The handmade mountain camp had matured into a nationally recognized outdoor education facility.",
    category: "renewal",
    era: "building",
  },
  {
    id: "chapel",
    year: "1966",
    sortYear: 1966,
    title: "A chapel is set among the pines",
    summary: "The open-air Clayton Herbert Memorial Chapel creates a quiet place for reflection at camp.",
    detail: "Herbert was remembered for directing the camp’s extensive craft program in the late 1950s and early 1960s. The chapel added a contemplative space to a campus built around action and activity.",
    significance: "Camp Lawton made room for stillness as well as skill-building.",
    category: "tradition",
    era: "building",
  },
  {
    id: "tohono-oodham",
    year: "1986",
    sortYear: 1986,
    title: "A historical name gains new context",
    summary: "The Papago Tribe officially adopts the name Tohono O’odham Nation, sharpening the need to understand Camp Lawton’s inherited terminology in its historical setting.",
    detail: "The history documents report that tribal leadership asked Papago Lodge to retain its established name. This timeline preserves period names only when explaining the historical record and uses Tohono O’odham for the Nation today.",
    significance: "Tradition is strongest when it is carried with context, care, and respect for living communities.",
    category: "tradition",
    era: "enduring",
  },
  {
    id: "aspen-fire",
    year: "2003",
    sortYear: 2003,
    title: "The Aspen Fire reaches the ridge",
    summary: "A devastating wildfire burns 84,750 acres and comes within roughly 100 yards of Camp Lawton’s southern boundary.",
    detail: "The core camp survived, but peripheral campsites and the Mountain Man program area were lost. The fire also destroyed hundreds of homes and businesses in nearby Summerhaven and left the surrounding forest deeply scarred.",
    significance: "Survival demanded a different relationship with fire, materials, water storage, and the forest itself.",
    category: "resilience",
    era: "enduring",
  },
  {
    id: "fire-hardening",
    year: "2004–06",
    sortYear: 2004,
    title: "Camp rebuilds for a hotter, drier future",
    summary: "Post-fire work replaces vulnerable canvas housing, renews more than 3,000 feet of waterline, and adds major storage at the Tank Farm.",
    detail: "Permanent cabins and elevated sleeping platforms reduced dependence on highly flammable canvas. The expanded water system strengthened day-to-day service as well as emergency fire response.",
    significance: "Recovery was not a return to the old camp; it was an investment in a more resilient one.",
    category: "resilience",
    era: "enduring",
    image: {
      src: "/images/campsite.jpg",
      alt: "Modern Camp Lawton cabins arranged beneath ponderosa pines",
      caption: "Permanent structures now shape campsites that were once dominated by canvas wall tents.",
    },
  },
  {
    id: "snow-collapse",
    year: "2010",
    sortYear: 2010,
    title: "Snow breaks the Ranger Cabin roof",
    summary: "Extreme late-season snow and wind collapse one side of the 1957 cabin roof and damage other camp structures.",
    detail: "Fourteen rafters broke under the load, and the campfire bowl was also heavily damaged. Volunteers mobilized quickly to clear hazards and rebuild before summer.",
    significance: "The same shared labor that built Camp Lawton continued to be the force that repaired it.",
    category: "resilience",
    era: "enduring",
  },
  {
    id: "dining-hall-unified",
    year: "2011",
    sortYear: 2011,
    title: "Two dining halls become one",
    summary: "The interior wall between the original dining hall and Butler Hall is removed to create a unified gathering space.",
    detail: "The renovation respected the layered 1947–1951 structure while adapting it to the way a modern camp needed to gather, eat, and run programs.",
    significance: "Historic buildings remained useful because each generation was willing to change them thoughtfully.",
    category: "renewal",
    era: "enduring",
  },
  {
    id: "peek-fountain",
    year: "2012–13",
    sortYear: 2012,
    title: "A memorial fountain is renewed",
    summary: "Former staff members rebuild the Leonard L. Peek Drinking Fountain, followed by a family rededication in 2013.",
    detail: "Originally built by Scouts and Scouters from Hayden, Arizona, the fountain connects a practical need—hydration—with the camp’s long practice of memorializing service in useful structures.",
    significance: "Restoration turned memory into something campers could still touch and use.",
    category: "tradition",
    era: "enduring",
  },
  {
    id: "coed-program",
    year: "2019",
    sortYear: 2019,
    title: "Resident camp opens wider",
    summary: "Camp Lawton integrates co-ed Scouts BSA resident programs for female youth and adult leaders.",
    detail: "The change extended the camp’s merit badge, leadership, and resident-camping opportunities to a broader community while requiring facilities and operations to evolve with the program.",
    significance: "A century-old place moved closer to serving every Scout who wanted a week on the mountain.",
    category: "renewal",
    era: "enduring",
  },
  {
    id: "master-plan",
    year: "2020",
    sortYear: 2020,
    title: "The Forest Service authorizes a new plan",
    summary: "The Coronado National Forest approves a master development framework for Camp Lawton’s 72-acre special-use footprint.",
    detail: "The plan created a path to rebuild and modernize facilities under contemporary safety and environmental requirements, including prefabricated gathering and kitchen infrastructure.",
    significance: "The next century of building would be guided by both camp needs and the responsibilities of operating on public forest land.",
    category: "renewal",
    era: "enduring",
  },
  {
    id: "centennial",
    year: "2021",
    sortYear: 2021,
    title: "Camp Lawton marks one hundred years",
    summary: "A centennial gathering and a new historical volume celebrate a century of Scouting on the mountain.",
    detail: "Butch Farabee’s “Camp Lawton, 1921–2021: A Century of Scouting,” published by the Tucson Corral of the Westerners, gathered the people, structures, and stories of the property into a durable record.",
    significance: "The centennial made clear that Camp Lawton’s greatest legacy is continuity: one generation preparing the place for the next.",
    category: "tradition",
    era: "enduring",
    image: {
      src: "/images/PXL_20260605_172059179.PANO.jpg",
      alt: "A wide view of Camp Lawton cabins and gathering spaces beneath the forest canopy",
      caption: "The camp’s present-day landscape holds layers of work completed across more than a century.",
    },
  },
  {
    id: "financial-restructure",
    year: "2025",
    sortYear: 2025,
    title: "Financial pressure forces hard choices",
    summary: "The Catalina Council redirects endowment funds toward operations and closes the resource-intensive alpine pool.",
    detail: "The documents describe a severe cash-flow challenge and a $389,000 reallocation from long-term funds. Council leaders also explored a statewide merger that could have changed Camp Lawton’s role and ended traditional week-long resident camp there.",
    significance: "The crisis made the question of local control—and the camp’s future purpose—immediate rather than abstract.",
    category: "resilience",
    era: "next",
  },
  {
    id: "independence-pivot",
    year: "2026",
    sortYear: 2026,
    title: "Local independence, a shorter summer model",
    summary: "On March 6, the council ends merger talks and chooses to continue independently in the near term.",
    detail: "Camp Director and Ranger MaryLou Chopelas reshaped the season around intensive three-day BSA and Cub Scout weekends. The pool remained closed, while Model Camp, Eagle Quest, and Order of the Arrow campfire traditions continued.",
    significance: "The newest chapter echoes the oldest one: use what is available, protect what matters, and build the next season with the people who show up.",
    category: "renewal",
    era: "next",
  },
];

export const historySourceDocuments = [
  "Camp Lawton Timeline Creation",
  "Camp Lawton History and Catalina Mountains",
  "Camp Lawton Spirit and Papago Symbolism",
  "Camp Lawton: History, Future, and Involvement",
];
