export type MapCategory = "campsite" | "program" | "amenity";

export type MapPoint = {
  x: number;
  y: number;
  label?: string;
};

export type CampMapLocation = {
  id: string;
  title: string;
  category: MapCategory;
  x: number;
  y: number;
  description: string;
  nearby: string;
  practical?: string;
  image?: string;
  imageAlt?: string;
  gallery?: { src: string; alt: string }[];
  points?: (MapPoint & { highlightImage?: string })[];
  capacity?: number;
  access?: string;
  meritBadges?: string[];
  highlightImage?: string;
};

export const mapCategoryLabels: Record<MapCategory, string> = {
  campsite: "Campsites",
  program: "Program areas",
  amenity: "Camp facilities",
};

export const campMapLocations: CampMapLocation[] = [
  {
    id: "staff-hill",
    highlightImage: "/map/staffHill.png",
    capacity: 0,
    access: "Staff Only",
    title: "Staff Hill",
    image: "/images/staff1960.jpg",
    category: "amenity",
    x: 47.1,
    y: 30.6,
    description: "During the summer camp season, Staff Hill is **Staff Only**, a designated space for the staff housing and time \"off stage\". Located on the north end of camp, it serves as the living quarters for the camp's employees. Since 2004, the area features high-quality cabins and four bathrooms with showers and flush toilets. More recently, the area was upgraded further to feature a full kitchen patio. By the way, during the rest of the year, you can rent out these facilities for your unit (or personal use) at https://catalinacouncil.org/outdoors/lawton/.",
    nearby: "North of Oglala campsite and west of Navajo campsite.",
    practical: "This is a staff area. Check with the Camp Office before heading up the hill.",
  },
  {
    id: "navajo",
    highlightImage: "/map/navajo.png",
    capacity: 12,
    access: "Campsite (special needs / vehicle access)",
    title: "Navajo Campsite",
    category: "campsite",
    x: 68.9,
    y: 26.7,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Navajo campsite badge",
    description: "The northeastern campsite is well suited for special needs units with vehicle access and no difficult trails to reach. It has a capacity to accommodate up to 12 campers.",
    nearby: "Above STEM and northeast of Al’s Well.",
    practical: "Navajo has direct vehicle access and is usually held for units that need that accommodation. Confirm every vehicle movement with camp staff.",
  },
  {
    id: "santa-cruz",
    highlightImage: "/map/santaCruz.png",
    capacity: 8,
    access: "Campsite (rustic privacy / large unit)",
    title: "Santa Cruz Campsite",
    category: "campsite",
    x: 23.2,
    y: 29.5,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Santa Cruz campsite badge",
    description: "Nestled in the northwestern-most corner of the camp and surrounded by old-growth forest, the Santa Cruz campsite is great if you like a bit of rustic privacy or if your unit is too big for the Pima campsite. It comfortably holds up to 8 campers.",
    nearby: "North of Pima campsite and across camp from Navajo.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "smellables-shed",
    highlightImage: "/map/smellables.png",
    access: "Publicly accessible (bear-safe storage)",
    title: "Smellables Shed",
    category: "amenity",
    x: 52.8,
    y: 32.5,
    description: "Bears can smell tempting scents for up to three miles and have the strength to break into most facilities in camp if they're motivated. All items that have an odor and might attract wildlife **must** be stored in the secured smellables shed, which is located next to the youth shower house. **Note:** The smellables shed is publicly accessible. Do not store any valuables in the Smellables Shed; if you need a secure place to store something, speak to camp administration.",
    nearby: "On the upper central trail network, west of Al’s Well.",
    practical: "Follow staff directions for food and scented-item storage. Wildlife-safe storage rules apply throughout camp.",
  },
  {
    id: "north-latrines",
    access: "Publicly accessible (restrooms / sinks / faucets)",
    title: "Latrines/KYBOs",
    category: "amenity",
    x: 28,
    y: 37,
    imageAlt: "Black line illustration of a camp latrine",
    description: "Each campsite (or campsite group) has a KYBO (Keep Your Bowels Open). KYBOs are what we call latrines/outhouses/restrooms. They are traditional non-flushing pit toilets, but private individual units with lockable doors. Each structure also has a sink, water faucet, hose, and a drinking fountain. **It is the unit's responsibility to keep them clean**.",
    nearby: "Distributed across the west, north, central, and eastern sides of camp.",
    practical: "Use the facility assigned or identified during orientation and report service concerns to staff.",
    points: [
      { x: 28.9, y: 37.1, label: "Northwest latrine", highlightImage: "/map/kybo4.png" },
      { x: 56.5, y: 29.2, label: "North-central latrine", highlightImage: "/map/kybo1.png" },
      { x: 72.8, y: 31.1, label: "Northeast latrine", highlightImage: "/map/kybo2.png" },
      { x: 78.6, y: 35.0, label: "East latrine", highlightImage: "/map/kybo3.png" },
      { x: 21.7, y: 50.7, label: "West latrine", highlightImage: "/map/kybo5.png" },
      { x: 27.9, y: 57.2, label: "Central-west latrine", highlightImage: "/map/kybo6.png" },
      { x: 71.6, y: 72.0, label: "Southeast latrine", highlightImage: "/map/kybo8.png" },
      { x: 30.9, y: 75.0, label: "Southwest latrine", highlightImage: "/map/kybo7.png" },
    ],
  },
  {
    id: "als-well",
    highlightImage: "/map/alswell.png",
    access: "Historic Landmark",
    title: "Al's Well",
    image: "/images/alsWellart.png",
    category: "amenity",
    x: 60.4,
    y: 36.7,
    description: "Named for Al Christensen who built the means to utilize the three springs near camp (known as Boy Scout Spring, Girl Scout Spring, and Lower Spring), Al's Well is an iconic landmark and drinking fountain on the trail to the youth shower house.",
    nearby: "Between Oglala campsite, STEM, and the Dining Hall approach.",
    practical: "Treat the well as a landmark; use only staff-designated sources for drinking water.",
  },
  {
    id: "oglala",
    highlightImage: "/map/oglala.png",
    capacity: 10,
    access: "Campsite (scenic creek bed)",
    title: "Oglala Campsite",
    category: "campsite",
    x: 39.9,
    y: 37.0,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Oglala campsite badge",
    description: "Surrounded by old-growth forest, ferns, and a creek bed, the Oglala campsite is arguably the most beautiful of the campsites in camp. It has a capacity of 10 campers.",
    nearby: "East of Pima, north of Zuni, and west of Al’s Well.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "stem",
    highlightImage: "/map/stem.png",
    meritBadges: ["Game Design", "Plumbing"],
    title: "STEM",
    category: "program",
    x: 72.5,
    y: 38.4,
    image: "/images/program.jpg",
    imageAlt: "Illustrated STEM program emblem with science and technology symbols",
    description: "While not traditional \"camp\" subjects, Science, Technology, Engineering, and Math are considered crucial skills for youth of this generation. The STEM program allows Scouts to learn everything from Game Design to Plumbing, greatly broadening the opportunities we can offer Scouts in camp. STEM is located in the Mike George Memorial Lodge (historically referred to as the Commissioner's Shack) between Navajo and the Camp Office.",
    nearby: "Below Navajo campsite and just north of the Camp Office.",
    practical: "Use this map for orientation; activities and meeting times will appear only in final authorized program information.",
  },
  {
    id: "pima",
    highlightImage: "/map/pima.png",
    capacity: 8,
    access: "Campsite",
    title: "Pima Campsite",
    category: "campsite",
    x: 21.6,
    y: 39.8,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Pima campsite badge",
    description: "Sister site to Oglala, Pima is a bit further back but equally nice. It accommodates up to 8 campers.",
    nearby: "South of Santa Cruz, west of Oglala, and north of Gila.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "camp-office",
    highlightImage: "/map/office.png",
    access: "All visitors must sign in",
    title: "Camp Office",
    category: "amenity",
    x: 74.5,
    y: 43.9,
    description: "Home of the camp administration, the Camp Office is a central hub for communication and management records, located near the main parking lot. The new patio area now allows for meetings and leisure. All visitors must immediately sign in here upon arrival.",
    nearby: "South of STEM, west of Eagle Quest, and northeast of the Parade Grounds.",
    practical: "Start here when you need camp staff direction, have a site question, or need to report a non-emergency concern.",
  },
  {
    id: "eagle-quest",
    highlightImage: "/map/eagleQuest.png",
    meritBadges: ["Citizenship in the Community", "Citizenship in the Nation", "Citizenship in the World", "Communication"],
    title: "Eagle Quest",
    category: "program",
    x: 83.0,
    y: 49.4,
    image: "/images/program.jpg",
    imageAlt: "Illustrated Eagle Quest program emblem",
    description: "Eagle Quest is the upper equivalent to Model Camp, committed to helping Scouts earn their Eagle rank. Located at the Eagle's Nest, this area focuses on essential required badges like Citizenship in the Nation, Citizenship in the World, Citizenship in the Community, and Communications.",
    nearby: "East of the Camp Office and above First Aid.",
    practical: "Activities and age guidance remain in development; check the authorized program information when it is published.",
  },
  {
    id: "dining-hall",
    highlightImage: "/map/diningHall.png",
    access: "Kitchen restricted (storm shelter)",
    title: "Dining Hall",
    image: "/images/diningHallSketch.png",
    category: "amenity",
    x: 61.1,
    y: 49.4,
    imageAlt: "Aerial view of Camp Lawton’s connected dining hall buildings and stone chimney",
    description: "With a commercial-quality kitchen and space for the entire camp, the dining hall is the central hub for meals and daily announcements. It also serves as the primary shelter during severe storms and lightning. The kitchen area is strictly restricted; campers and leaders may not enter without explicit permission from the Cook or Camp Director.",
    nearby: "Beside the Parade Grounds and north of Nature.",
    practical: "The Dining Hall is the primary storm shelter unless staff directs otherwise. Continuous ringing of its large bell is the campwide emergency alarm.",
  },
  {
    id: "campfire",
    highlightImage: "/map/campfireBowl.png",
    title: "Campfire Bowl",
    image: "/images/logsCrowd2026.jpg",
    category: "program",
    x: 50.6,
    y: 85.2,
    imageAlt: "Black line illustration of a campfire",
    description: "The Campfire Bowl is the gathering place for the camp's opening and closing programs. It hosts the Friday night Camper Campfire, where troops perform pre-approved skits and songs, as well as the staff campfires.",
    nearby: "One is west of Oglala; the larger gathering area is between Chapel and the ranges.",
    practical: "Fire restrictions can change without warning. Use a fire only when current conditions and camp staff explicitly allow it.",
    points: [
      { x: 28.5, y: 47.4, label: "West campfire area" },
      { x: 49.7, y: 82.9, label: "Lower campfire area" },
    ],
  },
  {
    id: "parade-grounds",
    highlightImage: "/map/paradeGrounds.png",
    title: "Parade Grounds",
    category: "amenity",
    x: 69.4,
    y: 49.9,
    description: "Located at the camp's flagpoles, the Parade Grounds serve as the mandatory assembly area for morning and evening flag ceremonies. Crucially, it is also the primary gathering point for the entire camp in the event of a continuous bell alarm or emergency drill.",
    nearby: "South of the Camp Office and east of the Dining Hall.",
    practical: "This is the primary campwide emergency assembly point. During an alarm, follow staff direction and report here for accountability.",
  },
  {
    id: "gila",
    highlightImage: "/map/gila.png",
    capacity: 17,
    access: "Campsite (largest)",
    title: "Gila Campsite",
    category: "campsite",
    x: 16.4,
    y: 54.9,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Gila campsite badge",
    description: "Gila is the largest individual campsite on the property, capable of accommodating up to 17 campers.",
    nearby: "West of Zuni and north of Yuma.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "zuni",
    highlightImage: "/map/zuni.png",
    capacity: 12,
    access: "Campsite (central)",
    title: "Zuni Campsite",
    category: "campsite",
    x: 35.5,
    y: 57.1,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Zuni campsite badge",
    description: "Zuni is a mid-sized campsite located centrally among the southern loop of sites. It can accommodate up to 12 campers. ```eof",
    nearby: "Below Oglala and near Adult Showers and Nature.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "nature",
    highlightImage: "/map/nature.png",
    meritBadges: ["Environmental Science", "Astronomy", "Forestry", "Mammal Study", "Plant Science"],
    title: "Nature",
    image: "/images/LAwtonstars.jpg",
    category: "program",
    x: 52.6,
    y: 56.0,
    imageAlt: "Illustrated Nature program emblem with trees, mountains, a bird, and a stream",
    description: "Also known as the Ecology area, the Nature Lodge is dedicated to the study of the natural world. Instructors here teach Merit Badges such as Environmental Science, Astronomy, Forestry, Mammal Study, and Plant Science.",
    nearby: "East of Zuni, south of the Dining Hall, and west of Handicraft.",
    practical: "Use established trails between activities and allow enough transition time from the outer campsites.",
  },
  {
    id: "adult-showers",
    highlightImage: "/map/adultShower.png",
    access: "Adult leaders only",
    title: "Adult Showers",
    category: "amenity",
    x: 44.3,
    y: 58.8,
    description: "Located just behind the Nature Lodge, the Adult Showers are separate facilities strictly reserved for adult leaders. These ADA-compliant structures feature flush toilets and are divided into separate men's and women's sides. Youth are not permitted in these facilities without specific medical/ADA authorization.",
    nearby: "Just west of Nature and north of Scoutcraft.",
    practical: "Follow posted access and privacy rules, and use only the facilities designated for your group.",
  },
  {
    id: "first-aid",
    highlightImage: "/map/healthLodge.png",
    access: "Health Lodge / Medic access",
    title: "Health Lodge",
    category: "amenity",
    x: 83.8,
    y: 61.4,
    description: "The Health Lodge is the domain of the Camp Health Officer (Medic) and the central location for treating injuries and illnesses. All prescription and over-the-counter medications for both youth and adults must be stored securely here and are distributed by the medical staff.",
    nearby: "East of Handicraft and south of Eagle Quest.",
    practical: "For urgent or serious concerns, notify camp staff immediately and follow the camp emergency plan.",
  },
  {
    id: "handicraft",
    highlightImage: "/map/handicraft.png",
    meritBadges: ["Art", "Basketry", "Leatherwork", "Wood Carving"],
    title: "Handicraft",
    category: "program",
    x: 64.4,
    y: 62.0,
    image: "/images/handicraft.jpg",
    imageAlt: "Illustrated Handicraft program emblem with scissors, paintbrushes, yarn, and thread",
    description: "Handicraft is the creative center of camp, operating on a largely independent study schedule. Scouts can work on artistic skills and earn badges like Art, Basketry, Leatherwork, and Wood Carving.",
    nearby: "East of Nature, west of First Aid, and north of Apache campsite.",
    practical: "Potential activities are still under review. Wait for the authorized program listing before making individual plans.",
  },
  {
    id: "scoutcraft",
    highlightImage: "/map/scoutcraft.png",
    meritBadges: ["Wilderness Survival", "Camping", "Pioneering", "Emergency Preparedness", "First Aid"],
    title: "Scoutcraft",
    image: "/images/backgroundlessNavigationSign.png",
    category: "program",
    x: 53.0,
    y: 66.7,
    imageAlt: "Black line illustration of a pioneering tower for Scoutcraft",
    description: "Also referred to as Outdoor Skills, Scoutcraft is where traditional Scouting thrives. The area provides instruction in Wilderness Survival, Camping, Pioneering, Emergency Preparedness, and First Aid. It is also the starting point for the camp's day and night-eye orienteering compass courses.",
    nearby: "Below Nature, west of Handicraft, and north of Model Camp.",
    practical: "Final skill instruction, project periods, and equipment guidance will be published after program approval.",
  },
  {
    id: "apache",
    highlightImage: "/map/apache.png",
    capacity: 11,
    access: "Campsite",
    title: "Apache Campsite",
    category: "campsite",
    x: 75.9,
    y: 67.7,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Apache campsite badge",
    description: "Apache is a mid-sized campsite that can accommodate up to 11 campers.",
    nearby: "South of First Aid and north of Cochise campsite.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "yuma",
    highlightImage: "/map/yuma.png",
    capacity: 11,
    access: "Campsite",
    title: "Yuma Campsite",
    category: "campsite",
    x: 19.8,
    y: 71.6,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Yuma campsite badge",
    description: "Yuma is located near the southern center of the camp loop and accommodates up to 11 campers.",
    nearby: "South of Gila and northwest of Hopi and Hohokam.",
    practical: "This is one of the farther sites from the central program areas, so include walking time in the day plan.",
  },
  {
    id: "model-camp",
    highlightImage: "/map/modelCamp.png",
    access: "Trail to First Class (Rank Skills)",
    title: "Model Camp",
    category: "program",
    x: 44.2,
    y: 73.4,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Model Camp emblem with a tent and pine trees",
    description: "Model Camp is the camp's premier Trail to First Class program. Designed as the ideal setup for newer Scouts, it offers self-paced instruction to help first and second-year campers complete early rank requirements.",
    nearby: "Southeast of Hohokam and southwest of Apache campsite.",
    practical: "This area may support first-year or rank skills; the final 2027 format has not been approved.",
  },
  {
    id: "cochise",
    highlightImage: "/map/cochise.png",
    capacity: 8,
    access: "Campsite (intimate)",
    title: "Cochise Campsite",
    category: "campsite",
    x: 79.2,
    y: 76.6,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Cochise campsite badge",
    description: "Cochise is a smaller, more intimate campsite capable of holding up to 8 campers.",
    nearby: "Below Apache and east of Chapel.",
    practical: "This is one of the farther sites from the Dining Hall and upper program areas, so plan transition time.",
  },
  {
    id: "hopi",
    highlightImage: "/map/hopi.png",
    capacity: 6,
    access: "Campsite (smallest)",
    title: "Hopi Campsite",
    category: "campsite",
    x: 12.2,
    y: 79.7,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Hopi campsite badge",
    description: "Hopi is the smallest designated campsite on the property, accommodating up to 6 campers.",
    nearby: "West of Hohokam and well southwest of Model Camp.",
    practical: "This is one of the farther sites from the central program areas, so include walking time in the day plan.",
  },
  {
    id: "hohokam",
    highlightImage: "/map/hohokam.png",
    capacity: 7,
    access: "Campsite",
    title: "Hohokam Campsite",
    category: "campsite",
    x: 24.9,
    y: 82.9,
    image: "/images/campsite.jpg",
    imageAlt: "Illustrated Hohokam campsite badge",
    description: "Hohokam is a smaller campsite located on the southern edge of the property, with a capacity of 7 campers.",
    nearby: "East of Hopi, south of Yuma, and west of Model Camp.",
    practical: "Plan to carry unit gear from the designated parking area unless staff gives different direction.",
  },
  {
    id: "chapel",
    highlightImage: "/map/chapel.png",
    access: "Open to all (Sunday evening interfaith service)",
    title: "Chapel",
    image: "/images/chapel.jpeg",
    category: "program",
    x: 66.4,
    y: 85.1,
    imageAlt: "The open-air Clayton Herbert Memorial Chapel with its stone altar and log benches among the pines",
    gallery: [
      { src: "/map/locations/chapel.webp", alt: "Illustrated chapel emblem with an open book and rising sun" },
    ],
    description: "The Clayton Herbert Memorial Chapel is an outdoor worship space open to all units and individuals for observing the twelfth point of the Scout Law. Camp staff lead a short, non-denominational interfaith service here on Sunday evenings.",
    nearby: "Southwest of Cochise and north of the main campfire and ranges.",
    practical: "Camp staff will announce any chapel, Scouts’ Own, or unit reflection opportunities for the session.",
  },
  {
    id: "archery",
    highlightImage: "/map/archery.png",
    meritBadges: ["Archery"],
    title: "Archery Range",
    category: "program",
    x: 38.2,
    y: 92.7,
    image: "/images/program.jpg",
    imageAlt: "Black line illustration of an arrow in an archery target",
    description: "Part of the Range and Target Activities (RATA) area, the Archery Range allows Scouts to hone their marksmanship and earn the Archery merit badge. Access requires strict obedience to Range Director commands and the use of all required protective equipment.",
    nearby: "Below the main campfire area and west of the Rifle Range.",
    practical: "Range availability is not final and always depends on approval, qualified supervision, and posted procedures.",
  },
  {
    id: "rifle-range",
    highlightImage: "/map/rifle.png",
    meritBadges: ["Rifle Shooting"],
    title: "Rifle Range",
    category: "program",
    x: 57.4,
    y: 95.8,
    image: "/images/program.jpg",
    imageAlt: "Black line illustration of a rifle inside a circle",
    description: "Also located in the RATA area, the Rifle Range operates under strict safety protocols. Due to United States Forest Service fire restrictions on the mountain, the camp utilizes CO2 air rifles (pellets) instead of traditional .22 caliber firearms, which fully comply with the Rifle Shooting merit badge requirements.",
    nearby: "Southeast of Archery and below the main campfire area.",
    practical: "Air-rifle programming runs only when approvals, equipment, range procedures, permit conditions, and qualified staff are all in place.",
  },
  {
    id: "black-ogre",
    access: "Restricted maintenance facility",
    highlightImage: "/map/ogre.png",
    title: "Black Ogre",
    category: "amenity",
    x: 78.7,
    y: 33.3,
    description: "The Black Ogre is the historical and colorful name given to the Ranger's tool shed and maintenance shop.",
    nearby: "East of Al's Well, near the front gate area.",
    practical: "Restricted to staff and authorized personnel only.",
  },
  {
    id: "peek-fountain",
    access: "Hydration Landmark",
    highlightImage: "/map/leekFountain.png",
    title: "Drinking Fountain (Peek Memorial)",
    image: "/images/2013PeekDrink1946.jpg",
    category: "amenity",
    x: 65.9,
    y: 54.0,
    description: "Located near the center of camp, this drinking fountain was originally built in the late 1940s by Scouts and Scouters from Hayden, AZ, in memory of Scoutmaster Leonard L. Peek. It was lovingly rebuilt in 2012 by former Camp Lawton staff members.",
    nearby: "Central intersection of trails, north of the Parade Grounds.",
    practical: "Filtered drinking water available 24/7.",
  },
  {
    id: "flammables-storage",
    access: "Restricted authorized personnel only",
    highlightImage: "/map/smellables.png",
    title: "Flammables Storage",
    category: "amenity",
    x: 52.8,
    y: 32.5,
    description: "A secure facility designated for the safe storage of all flammable materials and chemicals used in camp operations and maintenance.",
    nearby: "Near the maintenance area and Smellables Shed.",
    practical: "Strictly off-limits to all youth and adult leaders.",
  },
  {
    id: "front-gate",
    access: "Vehicle speed limit: 10 MPH",
    highlightImage: "/map/mainGate.png",
    title: "Front Gate",
    image: "/images/oldgates.jpeg",
    category: "amenity",
    x: 85.5,
    y: 41.0,
    description: "The main entrance to Camp Lawton is named for James M. Lawton, a former Catalina Council President for whom the camp is named.",
    nearby: "Northeast entrance of the camp.",
    practical: "Keep gate closed at all times. All vehicles must park in the main lot.",
  },
  {
    id: "quartermaster",
    access: "Gear & tool checkout",
    highlightImage: "/map/lowerStaff.png",
    title: "Quartermasters",
    category: "amenity",
    x: 51.7,
    y: 41.7,
    description: "The Quartermasters area serves as the central supply and logistics hub for camp operations, storing gear, tools, and program materials.",
    nearby: "Lower Staff area, west of the Camp Office.",
    practical: "Check out campsite tools, flags, and equipment during posted hours.",
  },
  {
    id: "ranger-cabin",
    access: "Private residence",
    highlightImage: "/map/rangerCabin.png",
    title: "Ranger's Cabin",
    image: "/images/vintageBryceLimingLyleBull1957.jpg",
    category: "amenity",
    x: 85.7,
    y: 34.0,
    description: "Built in 1957 by a massive effort of volunteers, contractors, Order of the Arrow members, and Scouts, this cabin serves as the on-site residence for the Camp Ranger.",
    nearby: "Near the Front Gate and main parking area.",
    practical: "Respect the Ranger's privacy; visit only for emergencies or by appointment.",
  },
  {
    id: "rendezvous",
    access: "Program and campfire hub",
    highlightImage: "/map/rendezvous.png",
    title: "Rendezvous Area",
    image: "/images/vintageFundayTomahawk.jpg",
    category: "program",
    x: 29.8,
    y: 47.7,
    description: "The Rendezvous Area is a program and campfire hub focused on cultural, historical, and physical activities.",
    nearby: "West side of the central loop, south of Model Camp.",
    practical: "Site of the Thursday night Gaga Ball tournament and mountain man programs.",
  },
  {
    id: "mountain-man",
    meritBadges: ["Pioneering", "Orienteering", "Wilderness Survival", "Hiking", "Backpacking", "Camping"],
    highlightImage: "/map/organizationRidge.png",
    title: "Mountain Man",
    category: "program",
    x: 73.4,
    y: 14.2,
    description: "Pioneering, Orienteering, Wilderness Survival, Hiking, Backpacking, and Camping area located near Organization Ridge.",
    nearby: "North end of camp near the Staff Hill trail.",
    practical: "Orienteering courses start here; prepare for high-altitude hiking.",
  },
  {
    id: "youth-showers",
    access: "Publicly accessible (showers / flush toilets / sinks)",
    highlightImage: "/map/youthShower.png",
    title: "Youth Showers",
    category: "amenity",
    x: 57.3,
    y: 33.5,
    description: "Located centrally on the upper trail loop near the Smellables Shed, the Youth Showers serve as the primary bathing facilities for youth campers. Features separate private stalls with hot water and flush toilets.",
    nearby: "Across the trail from Al's Well and next to the Smellables Shed.",
    practical: "Available 24/7. Units should establish a cleaning rotation to ensure facilities remain sanitary throughout the week.",
  },
];